@StatWeaver.Engine.API_HostAddress = https://localhost:7285


GET {{StatWeaver.Engine.API_HostAddress}}/api/games

###

POST {{StatWeaver.Engine.API_HostAddress}}/api/games
Content-Type: application/json

{
  "Identification": "G1",
  "Name": "The Witcher 3",
  "IsActive": true
}

###

@aId=1
DELETE {{StatWeaver.Engine.API_HostAddress}}/api/games/{{aId}}

###

GET {{StatWeaver.Engine.API_HostAddress}}/api/games/{{aId}}

###

PUT {{StatWeaver.Engine.API_HostAddress}}/api/games/{{aId}}
Content-Type: application/json

{
  "Name": "Fallout 4",
  "IsActive": true
}

###

GET {{StatWeaver.Engine.API_HostAddress}}/api/gameversions

###

POST {{StatWeaver.Engine.API_HostAddress}}/api/gameversions
Content-Type: application/json

{
  "Name": "Fallout 4",
  "IsActive": true
}

###

DELETE {{StatWeaver.Engine.API_HostAddress}}/api/gameversions/{{aId}}

###

GET {{StatWeaver.Engine.API_HostAddress}}/api/gameversions/{{aId}}

###

PUT {{StatWeaver.Engine.API_HostAddress}}/api/gameversions/{{aId}}
Content-Type: application/json

{
  "Name": "Fallout 4",
  "IsActive": true
}

###
